version: "3.9"
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks: 
      - mongodb
    volumes: 
      - mongodb:/data/db
      - mongodb_config:/data/configdb
    restart: always
    
    
networks:
  mongodb:

volumes:
  mongodb:
  mongodb_config: